### PR TITLE
.Net Standard 2.0 support

### PR DESCRIPTION
**Pull request by Thieum**
- added .gitignore to ignore build folders, .vs folder, and generated AssemblyInfoCommon.cs / xml doc
- migrated Ookii.CommandLine to netstandard2.0
- migrated all projects dependending on the netstandard2.0 lib to .net framework 4.6.1
- defined package infos directly in Ooki.CommandLine (auto increment build number don't seem to be a thing anymore in .net standard / core)
- Generate Package on build
- Replace references from codeplex to github

### CODE REVIEW

**Comment by Thieum** [comment]
Nuget summary is missing from the UI for the package in Visual Studio, there's a ticket that could be reopened here: https://developercommunity.visualstudio.com/content/problem/175015/nuget-package-summary-not-supported-in-vs-ui.html

Commented on it about the issue.

**Comment by Thieum** [comment]
@SvenGroot this PR still fixes a few url and settings - let me know if you want a new PR or new PRs for specific points.

**Comment by SvenGroot** [comment]
Hi @Thieum. I don't think I ever noticed this PR. I haven't done anything with this project in quite a while and only updated it to .Net Standard because I needed it for something myself. :)

Since I ended up using multi-targeting (the library is now built for .Net Framework 2.0 and .Net Standard 2.0), I don't think it's necessary to modify the target framework of the other projects, unless you know of a good reason to do so. I will fix the URLs however, thanks for notifying me of that.

**Comment by Thieum** [comment]
@SvenGroot no, no other reason than being compatible with .net standard. Thanks for the update!

**Pull request closed without merging**
